sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
    packages:
      - cmake
      - cmake-data
      - g++-7


before_install:
  - export CXX="g++-7"
  - export CC="gcc-7"
  - mkdir Build
  - cd Build
  - cmake ..
  - cd ..

script: 
  - g++-6 --version
  - cd Build
  - make
  - cd ..
